### ISSUE TITLE
Fails on non-standard aspect-ratios

### ISSUE THREAD

**Issue by wallace11** [amietn/vcsi#53] opened 2019-01-11 04:48 UTC
As the title says. Confirmed on multiple videos with this command:
```
vcsi video.mp4 -t -w 850 -g 3x4 -o output.jpg
```
This is the error I'm getting:
```
Traceback (most recent call last):
  File "/usr/bin/vcsi", line 11, in <module>
    load_entry_point('vcsi==7', 'console_scripts', 'vcsi')()
  File "/usr/lib/python3.7/site-packages/vcsi/__init__.py", line 3, in main
    vcsi.vcsi.main()
  File "/usr/lib/python3.7/site-packages/vcsi/vcsi.py", line 1331, in main
    process_file(filename, args)
  File "/usr/lib/python3.7/site-packages/vcsi/vcsi.py", line 1343, in process_file
    verbose=args.is_verbose)
  File "/usr/lib/python3.7/site-packages/vcsi/vcsi.py", line 93, in __init__
    self.compute_display_resolution()
  File "/usr/lib/python3.7/site-packages/vcsi/vcsi.py", line 157, in compute_display_resolution
    sample_aspect_ratio = self.video_stream["sample_aspect_ratio"]
KeyError: 'sample_aspect_ratio'
```
And a sample file `mediainfo`:
```
Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L3.1
Format settings                          : CABAC / 4 Ref Frames
Format settings, CABAC                   : Yes
Format settings, ReFrames                : 4 frames
Codec ID                                 : avc1
Codec ID/Info                            : Advanced Video Coding
Duration                                 : 48 min 5 s
Bit rate                                 : 903 kb/s
Maximum bit rate                         : 1 940 kb/s
Width                                    : 836 pixels
Height                                   : 626 pixels
Display aspect ratio                     : 4:3
Frame rate mode                          : Constant
Frame rate                               : 13.789 FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.125
Stream size                              : 311 MiB (100%)
Writing library                          : x264 core 155 r2917 0a84d98
Encoding settings                        : cabac=1 / ref=3 / deblock=1:0:0 / analyse=0x3:0x113 / me=hex / subme=7 / psy=1 / psy_rd=1.00:0.00 / mixed_ref=1 / me_range=16 / chroma_me=1 / trellis=1 / 8x8dct=1 / cqm=0 / deadzone=21,11 / fast_pskip=1 / chroma_qp_offset=-2 / threads=6 / lookahead_threads=1 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=3 / b_pyramid=2 / b_adapt=1 / b_bias=0 / direct=1 / weightb=1 / open_gop=0 / weightp=2 / keyint=250 / keyint_min=13 / scenecut=40 / intra_refresh=0 / rc_lookahead=40 / rc=crf / mbtree=1 / crf=22.0 / qcomp=0.60 / qpmin=0 / qpmax=69 / qpstep=4 / ip_ratio=1.40 / aq=1:1.00
Encoded date                             : UTC 2018-11-20 17:12:21
Tagged date                              : UTC 2018-11-20 17:12:21
Codec configuration box                  : avcC
```
Finally, `vcs` version:
```
→ vcsi --version     
vcsi version 7
```

**Comment by amietn** [comment] 2019-01-11 08:53
This issue is a duplicate of #45 
The problem you describe was fixed. You can use the git master version or the PyPi version which both include the fix. `vcsi --version` should say `vcsi version 7.0.7`.

**Closed by amietn** 2019-01-11 08:53 UTC
